import Head from "next/head";
import Footer from "../macro/sections/footer";
import Navbar from "../micro/navbar";

export default function UserLayout({ children }) {
  return (
    <>
      <Head>
        <title>Peduli Lansia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
        <meta lang="id" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
